Report error in bde schema loader

diff --git a/scripts/linz-lds-bde-schema-load.in b/scripts/linz-lds-bde-schema-load.in
--- a/scripts/linz-lds-bde-schema-load.in
+++ b/scripts/linz-lds-bde-schema-load.in
@@ -55,7 +55,10 @@ OPTS=
 if test "${EXTENSION_MODE}" = "off"; then
     OPTS="--noextension"
 fi
-${LOADER} ${OPTS} $DB_NAME || exit 1
+${LOADER} ${OPTS} $DB_NAME || {
+    echo "${LOADER} exited with an error" >&2
+    exit 1
+}
 
 export PGDATABASE=$DB_NAME
 (
